### ISSUE TITLE
remove systemctl start pipwn

### ISSUE THREAD

**Issue by nickcat325** [stooged/PI-Pwn#24]
Thank you for your work. I see you took my suggestion to clone the repo on the pi.
I have another suggestion. You can remove `sudo systemctl start pipwn` from install.sh as the pi restarts right after. (systemctl enable is necessary )

**Comment by stooged** [comment]
wasnt aware you suggested it sorry, the change to the install method was necessary to support armbian because it does not setup the bootfs partition to be accessible when you place the sd card into the pc so the user could not copy the pppwn folder.

this was done to support the rock pi 4c+ but it also allows you to use armbian minimal for raspberry pi if you do not want to use pi os lite.

thanks for the `sudo systemctl start pipwn` suggestion.
